name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        run: make
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy
        run: bash scripts/update-gh-pages.sh
